-- passport
USE master;
GO
CREATE DATABASE passdb COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE passdb SET READ_COMMITTED_SNAPSHOT ON;
GO
CREATE LOGIN x3dpass WITH PASSWORD = 'Passport123';
GO
CREATE LOGIN x3dpassadmin WITH PASSWORD = 'Passport123';
GO
USE passdb;
GO
CREATE USER x3dpass FOR LOGIN x3dpass WITH DEFAULT_SCHEMA = passdb;
GO
CREATE USER x3dpassadmin FOR LOGIN x3dpassadmin WITH DEFAULT_SCHEMA = passdb;
GO
CREATE SCHEMA passdb AUTHORIZATION x3dpassadmin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::passdb TO x3dpassadmin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SCHEMA::passdb TO x3dpass;
GO
CREATE DATABASE passtkdb COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE passtkdb SET READ_COMMITTED_SNAPSHOT ON;
GO
CREATE LOGIN x3dpasstokens WITH PASSWORD = 'Passport123';
GO
USE passtkdb;
GO
CREATE USER x3dpasstokens FOR LOGIN x3dpasstokens WITH DEFAULT_SCHEMA = passtkdb;
GO
CREATE SCHEMA passtkdb AUTHORIZATION x3dpasstokens;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::passtkdb TO x3dpasstokens;
GO
-- dashboard
USE master;
GO
CREATE DATABASE dashdb COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE dashdb SET READ_COMMITTED_SNAPSHOT ON;
GO
CREATE LOGIN x3ddash WITH PASSWORD = 'Passport123';
GO
CREATE LOGIN x3ddashadmin WITH PASSWORD = 'Passport123';
GO
USE dashdb;
GO
CREATE USER x3ddash FOR LOGIN x3ddash WITH DEFAULT_SCHEMA = dashdb;
GO
CREATE USER x3ddashadmin FOR LOGIN x3ddashadmin WITH DEFAULT_SCHEMA = dashdb;
GO
CREATE SCHEMA dashdb AUTHORIZATION x3ddashadmin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::dashdb TO x3ddashadmin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SCHEMA::dashdb TO x3ddash;
GO
-- Space 
use master;
GO
CREATE DATABASE [spacedb] ON PRIMARY (NAME=[spacedb],       
FILENAME='/db/system/spacedb.mdf',SIZE=500MB, FILEGROWTH=10MB) , 
FILEGROUP [I1_DATA] (NAME=[I1_DATA] , FILENAME='/db/system/I1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB) , 
FILEGROUP [I1_INDEX] (NAME=[I1_INDEX] , FILENAME='/db/system/I1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB), 
FILEGROUP [M1_DATA] (NAME=[M1_DATA] , FILENAME='/db/system/M1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB), 
FILEGROUP [M1_INDEX] (NAME=[M1_INDEX] , FILENAME='/db/system/M1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB), 
FILEGROUP [V1_DATA] (NAME=[V1_DATA] , FILENAME='/db/system/V1_DATA.mdf',SIZE=500MB,FILEGROWTH=10MB), 
FILEGROUP [V1_INDEX] (NAME=[V1_INDEX] , FILENAME='/db/system/V1_INDEX.mdf',SIZE=500MB,FILEGROWTH=10MB)
LOG ON (NAME=[spacedb_log] ,FILENAME='/db/system/spacedb.ldf',SIZE=100MB) 
COLLATE Latin1_General_100_CI_AS;
GO      
ALTER DATABASE [spacedb] SET AUTO_CLOSE OFF ; 
GO
ALTER DATABASE [spacedb] SET READ_COMMITTED_SNAPSHOT ON; 
GO
ALTER DATABASE [spacedb] SET AUTO_CREATE_STATISTICS ON;
GO 
ALTER DATABASE [spacedb] SET AUTO_UPDATE_STATISTICS ON;
GO
ALTER DATABASE [spacedb] SET AUTO_UPDATE_STATISTICS_ASYNC ON;
GO
CREATE LOGIN m1 WITH PASSWORD = 'Passport123';
GO
USE spacedb;
GO
CREATE USER m1 FOR LOGIN m1 WITH DEFAULT_SCHEMA = spacedb;
GO
CREATE SCHEMA spacedb AUTHORIZATION m1;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::spacedb TO m1;
GO
-- 3dswym
USE master;
GO
CREATE DATABASE x3dswym_social COLLATE Latin1_General_100_CI_AS;
GO
CREATE DATABASE x3dswym_media COLLATE Latin1_General_100_CI_AS;
GO
CREATE DATABASE x3dswym_widget COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE x3dswym_social SET READ_COMMITTED_SNAPSHOT ON;
GO
ALTER DATABASE x3dswym_media SET READ_COMMITTED_SNAPSHOT ON;
GO
ALTER DATABASE x3dswym_widget SET READ_COMMITTED_SNAPSHOT ON;
GO
CREATE LOGIN x3ds WITH PASSWORD = 'Passport123';
GO
CREATE LOGIN x3ds_admin WITH PASSWORD = 'Passport123';
GO
USE x3dswym_social;
GO
CREATE USER x3ds FOR LOGIN x3ds WITH DEFAULT_SCHEMA = x3dswym_social;
GO
CREATE USER x3ds_admin FOR LOGIN x3ds_admin WITH DEFAULT_SCHEMA = x3dswym_social;
GO
CREATE SCHEMA x3dswym_social AUTHORIZATION x3ds_admin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::x3dswym_social TO x3ds_admin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::x3dswym_social TO x3ds;
GO
USE x3dswym_media;
GO
CREATE USER x3ds FOR LOGIN x3ds WITH DEFAULT_SCHEMA = x3dswym_media;
GO
CREATE USER x3ds_admin FOR LOGIN x3ds_admin WITH DEFAULT_SCHEMA = x3dswym_media;
GO
CREATE SCHEMA x3dswym_media AUTHORIZATION x3ds_admin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::x3dswym_media TO x3ds_admin;
GO
GRANT CREATE TABLE ON DATABASE::x3dswym_media TO x3ds;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SCHEMA::x3dswym_media TO x3ds;
GO
USE x3dswym_widget;
GO
CREATE USER x3ds FOR LOGIN x3ds WITH DEFAULT_SCHEMA = x3dswym_widget;
GO
CREATE USER x3ds_admin FOR LOGIN x3ds_admin WITH DEFAULT_SCHEMA = x3dswym_widget;
GO
CREATE SCHEMA x3dswym_widget AUTHORIZATION x3ds_admin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::x3dswym_widget TO x3ds_admin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE, ALTER ON SCHEMA::x3dswym_widget TO x3ds;
GO
-- COMMENT
USE master;
GO
CREATE DATABASE x3dcomment COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE x3dcomment SET READ_COMMITTED_SNAPSHOT ON;
GO
-- CREATE LOGIN x3ds WITH PASSWORD = 'Passport123';
-- CREATE LOGIN x3ds_admin WITH PASSWORD = 'Passport123';
USE x3dcomment;
GO
CREATE USER x3ds FOR LOGIN x3ds WITH DEFAULT_SCHEMA = x3dcomment;
GO
CREATE USER x3ds_admin FOR LOGIN x3ds_admin WITH DEFAULT_SCHEMA = x3dcomment;
GO
CREATE SCHEMA x3dcomment AUTHORIZATION x3ds_admin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::x3dcomment TO x3ds_admin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::x3dcomment TO x3ds;
GO
-- NOTIFICATION
USE master;
GO
CREATE DATABASE x3dnotification COLLATE Latin1_General_100_CI_AS;
GO
ALTER DATABASE x3dnotification SET READ_COMMITTED_SNAPSHOT ON;
GO
-- CREATE LOGIN x3ds WITH PASSWORD = 'Passport123';
-- CREATE LOGIN x3ds_admin WITH PASSWORD = 'Passport123';
USE x3dnotification;
GO
CREATE USER x3ds FOR LOGIN x3ds WITH DEFAULT_SCHEMA = x3dnotification;
GO
CREATE USER x3ds_admin FOR LOGIN x3ds_admin WITH DEFAULT_SCHEMA = x3dnotification;
GO
CREATE SCHEMA x3dnotification AUTHORIZATION x3ds_admin;
GO
GRANT CREATE TABLE, ALTER, SELECT, INSERT, UPDATE, DELETE ON DATABASE::x3dnotification TO x3ds_admin;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::x3dnotification TO x3ds;
GO
